--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28/12/2019 10:27:05 p. m.
-- Server version: 8.0.18
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE database_links;

--
-- Drop table `sessions`
--
DROP TABLE IF EXISTS sessions;

--
-- Drop table `links`
--
DROP TABLE IF EXISTS links;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE database_links;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(16) NOT NULL,
  password varchar(60) NOT NULL,
  fullname varchar(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `links`
--
CREATE TABLE links (
  id int(11) NOT NULL AUTO_INCREMENT,
  title varchar(150) NOT NULL,
  url varchar(255) NOT NULL,
  description text DEFAULT NULL,
  user_id int(11) DEFAULT NULL,
  create_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 27,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE links
ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
REFERENCES users (id);

--
-- Create table `sessions`
--
CREATE TABLE sessions (
  session_id varchar(128) binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  expires int(11) UNSIGNED NOT NULL,
  data text binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table users
--
-- Table database_links.users does not contain any data (it is empty)

-- 
-- Dumping data for table sessions
--
INSERT INTO sessions VALUES
('2LVHw390orF68ZoST2_0X4Kt-PKC-wgg', 1577672669, '{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"flash":{}}'),
('jbPdVs0MibuOq2IGg9m9NUqibm6T0kd5', 1577672042, '{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"flash":{}}');

-- 
-- Dumping data for table links
--
INSERT INTO links VALUES
(25, 'Freilin Jose desde el cell', 'http://www.fabebook.xom', 'Skksjejd', NULL, '2019-12-28 22:13:35');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;